# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentsInfo',
            fields=[
                ('student_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15)),
                ('batch', models.IntegerField()),
                ('department', models.CharField(max_length=5)),
                ('section', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'students_info',
            },
        ),
    ]
