# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 08:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeachersInfo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('teacher_code', models.CharField(max_length=15)),
                ('teacher_name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('is_active', models.BooleanField()),
                ('is_superuser', models.BooleanField()),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
            ],
            options={
                'db_table': 'teachers_info',
            },
        ),
        migrations.CreateModel(
            name='ClassManagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField()),
                ('batch', models.IntegerField()),
                ('section', models.CharField(max_length=5)),
                ('subject', models.ForeignKey(db_column='subject', on_delete=django.db.models.deletion.CASCADE, to='subjects.SubjectsInfo')),
                ('teacher', models.ForeignKey(db_column='teacher', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'class_management',
            },
        ),
    ]
